// PPA-Lite 覆盖率排除文件（M4-04 覆盖率过滤登记）
// 仅排除 spec 强制的结构性不可达翻转位：§4.1 PREADY≡1、§5.2 无 CSR 字段落在 bit>=8。
// 登记见 doc/evidence/v0.4.0/coverage-exclude-registration.md。
// ExclMode: default
MODULE: apb_slave_if
Toggle PRDATA [8]
Toggle PRDATA [9]
Toggle PRDATA [10]
Toggle PRDATA [11]
Toggle PRDATA [12]
Toggle PRDATA [13]
Toggle PRDATA [14]
Toggle PRDATA [15]
Toggle PRDATA [16]
Toggle PRDATA [17]
Toggle PRDATA [18]
Toggle PRDATA [19]
Toggle PRDATA [20]
Toggle PRDATA [21]
Toggle PRDATA [22]
Toggle PRDATA [23]
Toggle PRDATA [24]
Toggle PRDATA [25]
Toggle PRDATA [26]
Toggle PRDATA [27]
Toggle PRDATA [28]
Toggle PRDATA [29]
Toggle PRDATA [30]
Toggle PRDATA [31]
Toggle PREADY "net PREADY"
MODULE: apb_if
Toggle prdata [8]
Toggle prdata [9]
Toggle prdata [10]
Toggle prdata [11]
Toggle prdata [12]
Toggle prdata [13]
Toggle prdata [14]
Toggle prdata [15]
Toggle prdata [16]
Toggle prdata [17]
Toggle prdata [18]
Toggle prdata [19]
Toggle prdata [20]
Toggle prdata [21]
Toggle prdata [22]
Toggle prdata [23]
Toggle prdata [24]
Toggle prdata [25]
Toggle prdata [26]
Toggle prdata [27]
Toggle prdata [28]
Toggle prdata [29]
Toggle prdata [30]
Toggle prdata [31]
Toggle pready "net pready"
